variable "consul_set_outputs" {
  default     = true
  description = "Should outputs be enabled for this module"
}

variable "consul_health_check_timeout" {
  default     = "120s"
  description = "The default timeout to wait for Consul to start"
}

variable "consul_data_folder" {
  description = "Data folder where output files including TLS certificates will be stored"
  default     = data("consul_kubernetes")
}

variable "consul_namespace" {
  default = "consul"
}

variable "monitoring_namespace" {
  default = "monitoring"
}

variable "consul_helm_values" {
  description = <<EOF
    Path for a consul helm values file that will used instead of the autogenerated file. The following variables will be ignored when this variables is set:
    * consul_acls_enabled
    * consul_tls_enabled
    * consul_gateway_enabled
    * consul_datacenter
    * consul_gateway_address
    * consul_federation_enabled
    * consul_federation_create_secret
  EOF

  default = "${file_dir()}/helm/consul_values.yaml"
}

variable "consul_helm_version" {
  default = "v1.1.1"
}

variable "consul_image" {
  default = "hashicorp/consul:1.15.1"
  //default = "hashicorp/consul:1.10.4"
}

variable "consul_k8s_image" {
  default = "hashicorp/consul-k8s-control-plane:1.1.1"
  //default = "hashicorp/consul-k8s:0.26.0-beta3"
}

variable "consul_envoy_image" {
  default     = "envoyproxy/envoy:v1.25.1"
  description = "Using the debian base images as alpine does not support arm"
  //default = "envoyproxy/envoy-alpine:v1.18.3"
}

variable "consul_ports_api" {
  default = 0
}

variable "consul_ports_rpc" {
  default = 8300
}

variable "consul_ports_lan" {
  default = 8301
}

variable "consul_ports_mesh_gateway" {
  default = 1443
}

variable "consul_ports_ingress_gateway" {
  default = [18080, 18443]
}

variable "consul_ports_release_controller" {
  default = 19443
}

variable "consul_acls_enabled" {
  default = false
}

variable "consul_tls_enabled" {
  default = false
}

variable "consul_datacenter" {
  default = "dc1"
}

variable "consul_ingress_gateway_enabled" {
  description = "Enable ingress gateways"
  default     = false
}

# Variables for Mesh Gateways
variable "consul_mesh_gateway_enabled" {
  description = "Enable mesh gateways"
  default     = false
}

variable "consul_mesh_gateway_address" {
  description = "Wan address for the mesh gateway"
  default     = ""
}

variable "consul_federation_enabled" {
  description = "Enable federation, required to use mesh gateways"
  default     = false
}

variable "consul_federation_create_secret" {
  description = "Create a federation secret?"
  default     = false
}

variable "consul_primary_datacenter" {
  description = "name of the primary datacenter when federation is enabled"
  default     = ""
}

variable "consul_primary_gateway" {
  description = "name of the primary gateway when federation is enabled"
  default     = ""
}

variable "consul_transparent_proxy_enabled" {
  description = "Enable the transparent proxy feature for then entire cluster for consul service mesh"
  default     = false
}

variable "consul_auto_inject_enabled" {
  description = "Enable the automatic injection of sidecar proxies for kubernetes pods"
  default     = false
}

variable "consul_auto_inject_deny_namespaces" {
  description = "List of Kubernetes namespaces where auto inject is ignored"
  default     = []
}

variable "consul_debug_enabled" {
  description = "Enable debug logging"
  default     = false
}

variable "consul_monitoring_enabled" {
  description = "Should the monitoring stack, Prometheus, Grafana, Loki, and Tempo be installed?"
  default     = false
}

variable "consul_monitoring_grafana_port" {
  description = "Port for grafana when monitoring enabled"
  default     = 8080
}

variable "consul_monitoring_prometheus_port" {
  description = "Port for prometheus when monitoring enabled"
  default     = 9090
}

variable "consul_release_controller_enabled" {
  description = "Should the Consul release controller be enabled?"
  default     = false
}

variable "consul_release_controller_helm_version" {
  description = "Helm chart version for Consul release controller"
  default     = "0.2.4"
}

# Variables for Monitoring module
variable "monitoring_k8s_cluster" {
  description = "Cluster to install monitoring, should be the same as the cluster for installing Consul"
  default     = var.consul_k8s_cluster
}

variable "monitoring_grafana_port" {
  description = "Set the monitoring module grafana port varaible, we do not expose this variable publically to cover interface changes"
  default     = var.consul_monitoring_grafana_port
}

variable "monitoring_prometheus_port" {
  description = "Set the monitoring module grafana port varaible, we do not expose this variable publically to cover interface changes"
  default     = var.consul_monitoring_prometheus_port
}

# Variables for SMI-Controller module
variable "smi_controller_k8s_cluster" {
  description = "Set the cluster to install the SMI controller to, we do not expose this variable publically to cover interface changes"
  default     = var.consul_k8s_cluster
}

variable "smi_controller_repository" {
  description = "Repository for the controller image"
  default     = var.consul_smi_controller_repository
}

variable "smi_controller_tag" {
  description = "Tag for the controller image"
  default     = var.consul_smi_controller_tag
}

variable "consul_ca_cert_file" {
  description = "location of an PEM encoded CA certificate to use for server certificate generation"
  default     = ""
}

variable "consul_ca_key_file" {
  description = "location of an PEM encoded CA certificate to use for server certificate generation"
  default     = ""
}

variable "consul_acl_token_file" {
  description = "location of the Consul replication ACL token to use for joining other servers"

  default = ""
}

variable "consul_releaser_acl_token_file" {
  description = "location of the ACL token that can be used by Consul Release Controller"
  default     = var.consul_acls_enabled ? "${var.consul_data_folder}/bootstrap_acl.token" : ""
}
